// Loading + read-only selectors over openpoke.ltm.demo_trace.v1 files.
// Everything here is defensive: traces are regenerated by the backend, so any field may be missing,
// and ids / timestamps change between runs. Nothing here knows what a scenario's outcome "should" be.

export const arr = (x) => (Array.isArray(x) ? x : []);
export const obj = (x) => (x && typeof x === "object" && !Array.isArray(x) ? x : {});

async function fetchJSON(url) {
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

/** Load index.json and every {scenario}.{mode}.json it lists (falls back to the default names). */
export async function loadRun(dir, defaultScenarios) {
  const base = dir.endsWith("/") ? dir : dir + "/";
  let index = null;
  try {
    index = await fetchJSON(base + "index.json");
  } catch {
    index = null;
  }
  const listed = arr(index?.files).concat(arr(index?.bonus_files));
  const names = listed.length
    ? listed
    : defaultScenarios.flatMap((s) => [`${s}.baseline.json`, `${s}.ltm.json`]);

  const scenarios = new Map();
  const errors = [];
  await Promise.all(
    names.map(async (name) => {
      const m = String(name).match(/^([a-z_]+)\.(baseline|ltm)\.json$/);
      if (!m) return;
      try {
        const doc = await fetchJSON(base + name);
        const entry = scenarios.get(m[1]) || { scenario: m[1], baseline: null, ltm: null };
        entry[m[2]] = doc;
        scenarios.set(m[1], entry);
      } catch (e) {
        errors.push(String(e.message || e));
      }
    }),
  );
  return { base, index, scenarios, errors };
}

// ---------- turns ----------

export const turns = (doc) => arr(doc?.turns).slice().sort((a, b) => (a.turn_index ?? 0) - (b.turn_index ?? 0));
export const isMessageTurn = (t) => typeof t?.text_safe === "string" && t.text_safe.length > 0;
export const turnByIndex = (doc, i) => turns(doc).find((t) => t.turn_index === i) || null;

/** Align baseline and LTM turns. Same script in both modes, so turn_index normally matches; fall back to text. */
export function alignTurns(base, ltm) {
  const b = turns(base);
  const l = turns(ltm);
  const rows = [];
  const usedB = new Set();
  for (const lt of l) {
    let bt = b.find((x) => x.turn_index === lt.turn_index && sameTurn(x, lt));
    if (!bt) bt = b.find((x) => !usedB.has(x) && sameTurn(x, lt));
    if (bt) usedB.add(bt);
    rows.push({ index: lt.turn_index, base: bt || null, ltm: lt });
  }
  for (const bt of b) if (!usedB.has(bt)) rows.push({ index: bt.turn_index, base: bt, ltm: null });
  return rows.sort((x, y) => (x.index ?? 0) - (y.index ?? 0));
}
function sameTurn(a, b) {
  if (a.kind !== b.kind) return false;
  if (isMessageTurn(a) || isMessageTurn(b)) return normText(a.text_safe) === normText(b.text_safe);
  return true;
}
const normText = (s) => String(s || "").replace(/\s+/g, " ").trim().toLowerCase();

// ---------- pipeline events ----------

export const pipeline = (doc) => arr(doc?.pipeline);
export const eventsForTurn = (doc, i) =>
  pipeline(doc)
    .filter((p) => p.turn_index === i)
    .sort((a, b) => (a.seq ?? 0) - (b.seq ?? 0) || String(a.ts).localeCompare(String(b.ts)));
export const eventsByStage = (doc, stage) => pipeline(doc).filter((p) => p.stage === stage);

/**
 * Group one turn's events into rows: one "turn" row (events without a candidate / clause) and one row per
 * extracted clause / candidate. A second ingest job inside the same trace (detail.duplicate === true on its
 * `extract` event) gets its own rows, so a delayed duplicate writer is visible as a separate actor.
 */
export function groupTurnEvents(events) {
  const rows = new Map();
  const order = [];
  const row = (key, init) => {
    if (!rows.has(key)) {
      rows.set(key, { key, events: [], ...init });
      order.push(key);
    }
    return rows.get(key);
  };
  row("turn", { kind: "turn" });
  const dupTraces = new Set();
  for (const e of events) {
    const d = obj(e.detail);
    if (e.stage === "extract" && d.duplicate === true) dupTraces.add(e.trace_id);
    const dup = dupTraces.has(e.trace_id);
    if (e.stage === "extract" && !e.candidate_id) {
      // job-level extract summary: attach to the job row
      row(dup ? "turn:dup" : "turn", { kind: "turn", duplicate: dup }).events.push(e);
      continue;
    }
    let key = null;
    if (e.candidate_id) key = `cand:${e.candidate_id}`;
    else if (e.stage === "extract.clause" && d.clause_index != null) key = `clause:${d.clause_index}`;
    if (!key) {
      row("turn", { kind: "turn" }).events.push(e);
      continue;
    }
    if (dup) key += ":dup";
    const r = row(key, { kind: "clause", duplicate: dup, candidate_id: e.candidate_id || null });
    if (e.stage === "extract.clause") {
      r.text = e.input_safe ?? r.text;
      r.clause_index = d.clause_index ?? r.clause_index;
      r.label = d.label ?? r.label;
    }
    if (!r.label && d.label) r.label = d.label;
    r.events.push(e);
  }
  return order.map((k) => rows.get(k)).filter((r) => r.events.length || r.kind !== "turn");
}

// ---------- memory state ----------

export const snapshots = (doc) =>
  arr(doc?.memory_state)
    .slice()
    .sort((a, b) => (a.after_turn ?? 0) - (b.after_turn ?? 0));
export const finalSnapshot = (doc) => {
  const s = snapshots(doc);
  return s.length ? s[s.length - 1] : null;
};

/** Latest-known facts per memory id across snapshots (keeps the last non-null display, e.g. after a purge). */
export function memoryCatalog(doc) {
  const cat = new Map();
  for (const snap of snapshots(doc)) {
    for (const m of arr(snap.memories)) {
      if (!m || !m.id) continue;
      const prev = cat.get(m.id) || {};
      cat.set(m.id, {
        ...prev,
        ...m,
        display: m.display ?? prev.display ?? null,
        last_known_text: m.canonical_text ?? prev.last_known_text ?? null,
        first_seen_after_turn: prev.first_seen_after_turn ?? snap.after_turn,
      });
    }
  }
  return cat;
}

export function memoryLabel(catalog, id) {
  const m = catalog.get(id);
  return m?.display || m?.last_known_text || (id ? `memory ${id.slice(-4)}` : "memory");
}

/** Chains of supersession inside a snapshot: [[oldest, …, newest], …] plus memories in no chain. */
export function supersessionChains(snap) {
  const mems = arr(snap?.memories);
  const byId = new Map(mems.map((m) => [m.id, m]));
  const next = new Map();
  const prev = new Map();
  for (const e of arr(snap?.edges)) {
    if (e?.kind !== "superseded_by") continue;
    next.set(e.from, e.to);
    prev.set(e.to, e.from);
  }
  for (const m of mems) {
    if (m.superseded_by_id && !next.has(m.id)) {
      next.set(m.id, m.superseded_by_id);
      prev.set(m.superseded_by_id, m.id);
    }
  }
  const chains = [];
  const inChain = new Set();
  for (const m of mems) {
    if (prev.has(m.id) || !next.has(m.id)) continue;
    const chain = [];
    let cur = m.id;
    const guard = new Set();
    while (cur && !guard.has(cur)) {
      guard.add(cur);
      chain.push(byId.get(cur) || { id: cur });
      inChain.add(cur);
      cur = next.get(cur);
    }
    chains.push(chain);
  }
  return { chains, singles: mems.filter((m) => !inChain.has(m.id)) };
}

// ---------- retrieval / probes ----------

export const retrievals = (doc) => arr(doc?.retrieval).slice().sort((a, b) => (a.turn_index ?? 0) - (b.turn_index ?? 0));
export const retrievalForTurn = (doc, i) => retrievals(doc).find((r) => r.turn_index === i) || null;
export const probes = (doc) => arr(doc?.probes).slice().sort((a, b) => (a.turn_index ?? 0) - (b.turn_index ?? 0));
export const probeForTurn = (doc, i) => probes(doc).find((p) => p.turn_index === i) || null;

/** model_context for a probe turn: probes[] entry, else the top-level model_context if it is that turn. */
export function modelContextForTurn(doc, i) {
  const p = probeForTurn(doc, i);
  if (p && p.model_context) return p.model_context;
  const mc = obj(doc?.model_context);
  return mc.turn_index === i ? mc : null;
}

/** Flag keys used in a model_context (contains_xxx → xxx). */
export function contextFlags(mc) {
  const keys = new Set();
  for (const k of Object.keys(obj(mc))) if (k.startsWith("contains_")) keys.add(k.slice(9));
  for (const sec of Object.values(obj(mc?.sections)))
    for (const k of Object.keys(obj(sec))) if (k.startsWith("contains_")) keys.add(k.slice(9));
  return [...keys];
}

// ---------- baseline observations ----------

export const observationsForTurn = (doc, i) => arr(doc?.baseline_observations).filter((o) => o.turn_index === i);
export function observationFlags(doc) {
  const keys = new Set();
  for (const o of arr(doc?.baseline_observations)) for (const k of Object.keys(obj(o.contains))) keys.add(k);
  return [...keys];
}

// ---------- assertions ----------

export const assertions = (doc) => arr(doc?.assertions);
export const assertionById = (doc, id) => assertions(doc).find((a) => a.id === id) || null;

// ---------- headline turn selection (generic, data-driven) ----------

const INTEREST = { SUPERSEDE: 5, FENCE_DROP: 6, DELETE: 5, REJECT: 3, INSERT: 2, NO_CANDIDATE: 1, MERGE: 2, CONTEST: 4 };

/** The most "eventful" message turn in a trace, based on its outcomes. */
export function headlineTurn(doc) {
  let best = null;
  let bestScore = -1;
  for (const t of turns(doc)) {
    if (!isMessageTurn(t) || t.kind === "probe") continue;
    const outs = arr(t.outcomes);
    const score =
      outs.length +
      outs.reduce((s, o) => s + (INTEREST[o.result] || 0), 0) +
      (new Set(outs.map((o) => o.decision)).size > 1 ? 4 : 0);
    if (score >= bestScore) {
      best = t;
      bestScore = score;
    }
  }
  return best || turns(doc).find(isMessageTurn) || null;
}

/** The probe the harness marked as headline (meta.headline_probe), else the first probe turn. */
export function headlineProbe(doc) {
  const want = doc?.meta?.headline_probe;
  const ps = turns(doc).filter((t) => t.kind === "probe");
  return ps.find((t) => t.probe === want) || ps[0] || null;
}

// ---------- value labels for flag keys (data-derived, used only for display) ----------

/**
 * Flag keys like old_value / new_value are abstract. Name them from the trace: canary labels (OLD_VALUE:python)
 * matched to memory displays, and the ends of a single supersession chain. Returns {} when nothing can be derived.
 */
export function deriveFlagLabels(ltm, base) {
  const out = {};
  const cat = ltm ? memoryCatalog(ltm) : new Map();
  const displays = [...cat.values()].map((m) => m.display).filter(Boolean);
  const canaries = arr(ltm?.canary_scan?.canaries).concat(arr(base?.canary_scan?.canaries));
  for (const c of canaries) {
    const m = String(c).match(/^([A-Z_]+):(.+)$/);
    if (!m || !/_VALUE$/.test(m[1])) continue;
    const key = m[1].toLowerCase();
    out[key] = displays.find((d) => d.toLowerCase() === m[2].toLowerCase()) || m[2];
  }
  const snap = finalSnapshot(ltm);
  const { chains } = supersessionChains(snap);
  if (chains.length === 1 && chains[0].length > 1) {
    const c = chains[0];
    out.old_value = out.old_value || c[0].display;
    out.new_value = c[c.length - 1].display || out.new_value;
  }
  for (const k of Object.keys(out)) if (!out[k]) delete out[k];
  return out;
}
